---
inherit_from: ../.rubocop.yml

Performance/CollectionLiteralInLoop:
  Enabled: false

RSpec/BeforeAfterAll:
  Exclude:
  - 'acceptance/**/*'
  - 'api/ipptool_spec.rb'

RSpec/DescribeClass:
  Enabled: false

RSpec/ImplicitSubject:
  EnforcedStyle: single_line_only

RSpec/InstanceVariable:
  Exclude:
  - 'api/ipptool_spec.rb'

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not

RSpec/RepeatedExample:
  Exclude:
  - 'classes/init_spec.rb'
