on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby: [ '2.7', '3.0', '3.1' ]
        puppet: [ '~> 7.0' ]
    name: Ruby ${{ matrix.ruby }} using Puppet ${{ matrix.puppet }}
    env:
      PUPPET_GEM_VERSION: ${{ matrix.puppet }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: gem install bundler -v 2.2.15
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - run: bundle config set without 'acceptance_testing metatools'
      - run: bundle install
      - uses: amancevice/setup-code-climate@v0
        with:
          cc_test_reporter_id: ${{ secrets.CC_TEST_REPORTER_ID }}
      - run: cc-test-reporter before-build
      - run: bundle exec rake github:actions
      - run: cc-test-reporter after-build
        # if: ${{ github.ref == 'refs/heads/main' }}

  release:
    name: PuppetForge release, GitHub release, GitHub pages
    needs: test
    if: ${{ github.ref == 'refs/heads/release' }}
    runs-on: ubuntu-20.04
    env:
      BLACKSMITH_FORGE_PASSWORD: ${{ secrets.BLACKSMITH_FORGE_PASSWORD }}
      BLACKSMITH_FORGE_URL: ${{ secrets.BLACKSMITH_FORGE_URL }}
      BLACKSMITH_FORGE_USERNAME: ${{ secrets.BLACKSMITH_FORGE_USERNAME }}
      PUPPET_GEM_VERSION: '~> 6.0'
      X_GITHUB_TOKEN: ${{ secrets.X_GITHUB_TOKEN }}
      X_GITHUB_USERNAME: ${{ secrets.X_GITHUB_USERNAME }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - run: gem install bundler -v 2.2.15
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - run: bundle config set without 'acceptance_testing metatools'
      - run: bundle install
      - run: bundle exec rake forge:release
      - run: bundle exec rake github:release
      - run: bundle exec rake github:pages
